package com.superbrown.superSpell.gwtApp.client.common.cheat;

/**
 */
public enum Cheat
{
    UNLOCK_MUSIC,
    SHOW_ALL_MISPELLINGS,
    CHALK_BOARD_BACKGROUND,
    PINK_BACKGROUND,
    BLUE_BACKGROUND,
    PURPLE_BACKGROUND,
    AQUA_BACKGROUND,
    BROWN_BACKGROUND,
    ORANGE_BACKGROUND,
    RED_BACKGROUND,
    BLACK_BACKGROUND,
    TURN_ON_THREE_STOOGES_SOUND, 
    TURN_ON_GOMER_PYLE_SOUND,
    SILENCE_SOUND,
//    READ_IMMEDIATELY_MODE,
    MASTERMIND,
    USE_PETER_MATH,
    CHALKBOARD_DOODLING,
    UNRECOGNIZED,
    MATH_TIMER_IN_SECONDS,
    NO_VALUE_ENTERED,
}
